-- =============================================================================
-- WaaS SEO: Migration 023 — Per-tenant SEO Keywords
-- PR #103 — WaaS SEO: Keyword injection + sitemap.xml
--
-- Adds seo_keywords TEXT[] to tenant_site_config so that AI-generated
-- keyword clusters can be stored and later injected into each tenant's
-- <meta name="keywords"> tag and structured data.
--
-- Also adds seo_last_generated_at so the admin UI can surface when keywords
-- were last refreshed, enabling scheduled regeneration.
--
-- Safe to re-run (all statements idempotent via IF NOT EXISTS).
-- Run AFTER 022_waas_site_build_status.sql
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Add seo_keywords column to tenant_site_config
--    TEXT[] — ordered list of SEO keyword phrases (max 20)
-- ---------------------------------------------------------------------------

ALTER TABLE tenant_site_config
  ADD COLUMN IF NOT EXISTS seo_keywords              TEXT[]      NULL,
  ADD COLUMN IF NOT EXISTS seo_keywords_provider     TEXT        NULL,   -- 'gemini' | 'perplexity' | 'fallback'
  ADD COLUMN IF NOT EXISTS seo_last_generated_at     TIMESTAMPTZ NULL;

-- ---------------------------------------------------------------------------
-- 2. Index on seo_last_generated_at for scheduled regeneration queries
--    (find tenants whose keywords are stale or never generated)
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_tenant_site_config_seo_generated_at
  ON tenant_site_config (seo_last_generated_at)
  WHERE seo_last_generated_at IS NULL OR seo_last_generated_at < NOW() - INTERVAL '30 days';

-- ---------------------------------------------------------------------------
-- 3. Comment the new columns for schema documentation
-- ---------------------------------------------------------------------------

COMMENT ON COLUMN tenant_site_config.seo_keywords IS
  'AI-generated SEO keyword phrases injected into <meta name="keywords">. Max 20 items. Generated by keyword-generator service.';

COMMENT ON COLUMN tenant_site_config.seo_keywords_provider IS
  'Provider used to generate seo_keywords: gemini | perplexity | fallback.';

COMMENT ON COLUMN tenant_site_config.seo_last_generated_at IS
  'Timestamp of last seo_keywords generation. NULL = never generated.';
